// site/components/footer/Footer.tsx
import LogoRepubliqueFrancaise from 'components/logo/LogoRepubliqueFrancaise';

export const Footer = () => {
  return (
    <footer className="fr-footer" role="contentinfo" id="footer">
      <div className="fr-container">
        <div className="fr-footer__body">
          <div className="fr-footer__brand">
            <LogoRepubliqueFrancaise />
            <picture>
              <img
                className="fr-footer__logo fr-ml-2w"
                width="128"
                height="146"
                src="/ademe.svg"
                alt="ADEME"
                loading="lazy"
              />
            </picture>
          </div>
          <div className="fr-footer__content">
            <p className="fr-footer__content-desc">
              Territoires en Transitions est une startup d&apos;État portée par
              l&apos;Agence de la Transition Écologique (ADEME) avec le soutien
              de l&apos;Agence Nationale de la Cohésion des Territoires (ANCT).
            </p>
            <ul className="fr-footer__content-list">
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="https://www.ademe.fr/"
                  target="_blank"
                  rel="noreferrer"
                >
                  ademe.fr
                </a>
              </li>
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="https://beta.gouv.fr/"
                  target="_blank"
                  rel="noreferrer"
                >
                  beta.gouv
                </a>
              </li>
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="https://territoireengagetransitionecologique.ademe.fr"
                  target="_blank"
                  rel="noreferrer"
                >
                  territoireengagetransitionecologique.ademe.fr
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div className="fr-footer__bottom">
          <ul className="fr-footer__bottom-list">
            <li className="fr-footer__bottom-item">
              <a className="fr-footer__bottom-link" href="/stats">
                Statistiques
              </a>
            </li>
            <li className="fr-footer__bottom-item">
              <span className="fr-footer__bottom-link">
                <a className="fr-footer__bottom-link" href="/accessibilite">
                  Accessibilité : non conforme
                </a>
              </span>
            </li>
            <li className="fr-footer__bottom-item">
              <a className="fr-footer__bottom-link" href="/mentions">
                Mentions légales
              </a>
            </li>
            <li className="fr-footer__bottom-item">
              <a
                className="fr-footer__bottom-link"
                href="https://www.ademe.fr/donnees-personnelles/"
                target="_blank"
                rel="noreferrer"
              >
                Données personnelles
              </a>
            </li>
            <li className="fr-footer__bottom-item">
              <a className="fr-footer__bottom-link" href="/cookies">
                Gestion des cookies
              </a>
            </li>
            <li className="fr-footer__bottom-item">
              <a
                className="fr-footer__bottom-link"
                href="https://github.com/betagouv/territoires-en-transitions"
                target="_blank"
                rel="noreferrer"
              >
                Code source
              </a>
            </li>
            <li className="fr-footer__bottom-item">
              <a className="fr-footer__bottom-link" href="/cgu">
                Conditions générales d’utilisation
              </a>
            </li>
          </ul>
          <div className="fr-footer__bottom-copy">
            <p>
              Sauf mention contraire, tous les contenus de ce site sont sous{' '}
              <a
                href="https://github.com/etalab/licence-ouverte/blob/master/LO.md"
                target="_blank"
                rel="noreferrer"
              >
                licence etalab-2.0
              </a>
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

// territoires-en-transitions.fr/src/components/Footer.svelte
<footer class="fr-footer fr-mt-10w" role="contentinfo" id="footer">
  <div class="fr-container">
    <div class="fr-footer__body">
      <div class="fr-footer__brand fr-enlarge-link">
        <p class="fr-logo">
          république
          <br>française
        </p>
        <div class="fr-header__ademe">
          <picture>
            <source srcset="./img/ademe.jpg 118w" sizes="118px">
            <img src="./img/ademe.jpg" alt="ADEME" loading="lazy">
          </picture>
        </div>
      </div>
    </div>
    <div class="fr-footer__bottom">
      <ul class="fr-footer__bottom-list">
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="#plan-du-site" target="_self">Plan du site</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="#mentions-legales" target="_self">Mentions légales</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="#statistiques" target="_self">Statistiques</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="https://www.ademe.fr/lademe/infos-pratiques/politique-protection-donnees-a-caractere-personnel" target="_blank" rel="noopener" title="Protection des données - nouvelle fenêtre">Protection des données</a>
        </li>
      </ul>
      <div class="fr-footer__bottom-copy">
        <p>Sauf mention contraire, tous les textes de ce site sont sous licence <a class="rf-link-licence" title="Licence etalab-2.0 sur le site etalab - nouvelle fenêtre" target="_blank" rel="noopener" href="https://www.etalab.gouv.fr/licence-ouverte-open-licence">etalab-2.0</a>
        </p>
      </div>
    </div>
  </div>
</footer>
