// app.territoiresentransitions.react/src/app/Layout/Footer/Footer.tsx
import {Link} from 'react-router-dom';
import LogoRepubliqueFrancaise from 'ui/logo/LogoRepubliqueFrancaise';
import ademeLogoImage from 'app/static/img/ademe.jpg';

const Footer = () => {
  return (
    <footer
      className="footer fr-footer fr-mt-10w"
      role="contentinfo"
      id="footer"
    >
      <div className="fr-container">
        {/* BODY */}
        <div className="lg:flex">
          <div className="fr-footer__brand flex-shrink-0">
            <LogoRepubliqueFrancaise />
            <div className="px-6">
              <img
                className="w-32"
                src={ademeLogoImage}
                alt="ADEME"
                loading="lazy"
              />
            </div>
          </div>
          <div className="fr-footer__content !mt-6 !flex-initial lg:!mt-0 lg:!ml-6">
            <h5 className="w-full mb-4">
              <a href="https://territoiresentransitions.fr" title="Accueil">
                Territoires en Transitions
              </a>
            </h5>
            <p className="fr-footer__content-desc">
              Territoires en transitions accompagne les collectivités afin de
              les aider à piloter plus facilement leur transition écologique.
            </p>
            <p className="fr-footer__content-desc">
              Vous rencontrez une difficulté ? Une suggestion pour nous aider à
              améliorer l'outil ?
              <br />
              Écrivez-nous à&nbsp;:&nbsp;
              <a href="mailto:aide@territoiresentransitions.fr?subject=Aide sur app.territoiresentransitions.fr">
                aide@territoiresentransitions.fr
              </a>
            </p>
            <ul className="fr-footer__content-list">
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="https://www.ademe.fr/"
                >
                  ademe.fr
                </a>
              </li>
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="https://beta.gouv.fr/"
                >
                  beta.gouv
                </a>
              </li>
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="https://territoireengagetransitionecologique.ademe.fr"
                >
                  territoireengagetransitionecologique.ademe.fr
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* MENTIONS LEGALES */}
        <div className="fr-footer__bottom">
          <ul className="fr-footer__bottom-list">
            <li className="fr-footer__bottom-item">
              <a
                className="fr-footer__bottom-link"
                href="https://territoiresentransitions.fr/mentions-legales/"
                target="_self"
              >
                Mentions légales
              </a>
            </li>
            <li className="fr-footer__bottom-item">
              <a
                className="fr-footer__bottom-link"
                href="https://www.ademe.fr/lademe/infos-pratiques/politique-protection-donnees-a-caractere-personnel"
                rel="external noreferrer"
                target="_blank"
              >
                Protection des données
              </a>
            </li>
            <li className="fr-footer__bottom-item">
              <Link className="fr-footer__bottom-link" to="/statistics">
                Statistiques
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// territoires-en-transitions.fr/src/components/Footer.svelte
<footer class="fr-footer fr-mt-10w" role="contentinfo" id="footer">
  <div class="fr-container">
    <div class="fr-footer__body">
      <div class="fr-footer__brand fr-enlarge-link">
        <p class="fr-logo">
          république
          <br>française
        </p>
        <div class="fr-header__ademe">
          <picture>
            <source srcset="static/img/ademe.jpg 118w" sizes="118px">
            <img src="static/img/ademe.jpg" alt="ADEME" loading="lazy">
          </picture>
        </div>
      </div>
    </div>
    <div class="fr-footer__bottom">
      <ul class="fr-footer__bottom-list">
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="/plan-du-site" target="_self">Plan du site</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="/mentions-legales" target="_self">Mentions légales</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="/statistiques" target="_self">Statistiques</a>
        </li>
        <li class="fr-footer__bottom-item">
          <a class="fr-footer__bottom-link" href="https://www.ademe.fr/lademe/infos-pratiques/politique-protection-donnees-a-caractere-personnel" target="_blank" rel="noopener" title="Protection des données - nouvelle fenêtre">Protection des données</a>
        </li>
      </ul>
      <div class="fr-footer__bottom-copy">
        <p>Sauf mention contraire, tous les textes de ce site sont sous licence <a class="rf-link-licence" title="Licence etalab-2.0 sur le site etalab - nouvelle fenêtre" target="_blank" rel="noopener" href="https://www.etalab.gouv.fr/licence-ouverte-open-licence">etalab-2.0</a>
        </p>
      </div>
    </div>
  </div>
</footer>
