// apps/app/src/app/Layout/Header/Header.tsx
'use client';

import { makeTdbCollectiviteUrl } from '@/app/app/paths';
import classNames from 'classnames';
import Image from 'next/image';
import { useState } from 'react';
import ademeSrc from '../../static/img/ademe.svg?url';
import { AccesRapide } from './AccesRapide';
import { MenuPrincipal } from './MenuPrincipal';
import { HeaderProps, HeaderPropsWithModalState } from './types';

/** Valeur de la hauteur sur header de l'application */
export const appHeaderHeight = 183;

/**
 * Affiche l'en-tête
 */
export const Header = (props: HeaderProps) => {
  // état ouverture menu mobile
  const [modalOpened, setModalOpened] = useState(false);
  // id du menu ouvert
  const [openedId, setOpenedId] = useState<string | null>(null);

  const propsWithState = {
    ...props,
    modalOpened,
    setModalOpened,
    openedId,
    setOpenedId,
  };

  return (
    <header role="banner" id="app-header" className="fr-header">
      <Body {...propsWithState} />
      <Menu {...propsWithState} />
    </header>
  );
};

/** Affiche les blocs "marque", "service" et les liens "accès rapides". Sur
 *  mobile, Le bloc "accès rapides" est masqué (mais est afiché par la modale
 *  incluse dans Menu). */
const Body = (props: HeaderPropsWithModalState) => {
  return (
    <div className="w-full max-w-[90rem] mx-auto px-2 md:px-4 lg:px-6">
      <div className="flex items-center justify-start -mx-4 lg:py-6">
        <div className="fr-header__brand fr-enlarge-link">
          <Brand {...props} />
          <div className="fr-header__service">
            <a
              href={
                props.currentCollectivite
                  ? makeTdbCollectiviteUrl({
                      collectiviteId: props.currentCollectivite.collectiviteId,
                      view: 'synthetique',
                    })
                  : '/'
              }
              title="Accueil - Territoires en Transitions"
            >
              <p className="fr-header__service-title m-0">
                Territoires en Transitions
              </p>
              <p className="fr-header__service-tagline m-0">
                Accompagner la transition écologique des collectivités
              </p>
            </a>
          </div>
        </div>
        <div className="fr-header__tools">
          <div className="fr-header__tools-links">
            <AccesRapide {...props} />
          </div>
        </div>
      </div>
    </div>
  );
};

/** Affiche les liens de la navigation principale. Les liens sont présentés dans
 * une modale sur mobile, accompagnés des liens "accès rapides". */
const Menu = (props: HeaderPropsWithModalState) => {
  const { modalOpened, setModalOpened } = props;

  return (
    <div
      id="modal-header__menu"
      className={classNames('fr-header__menu fr-modal', {
        'fr-modal--opened': modalOpened,
      })}
      role={modalOpened ? 'dialog' : undefined}
    >
      <div className="w-full max-w-[90rem] mx-auto px-2 md:px-4 lg:px-6">
        <button
          aria-controls="modal-header__menu"
          className="fr-btn fr-btn--close"
          onClick={() => setModalOpened(false)}
        >
          Fermer
        </button>
        <MenuPrincipal {...props} />
        <div className="fr-header__menu-links">
          <AccesRapide {...props} />
        </div>
      </div>
    </div>
  );
};

/** Affiche le bloc "marque" */
const Brand = (props: HeaderPropsWithModalState) => {
  const { modalOpened, setModalOpened } = props;

  return (
    <div className="fr-header__brand-top">
      <div className="fr-header__logo">
        <p className="fr-logo">
          République
          <br />
          Française
        </p>
      </div>
      <div className="fr-header__operator">
        <div className="fr-grid-row">
          <Image
            priority={false}
            src={ademeSrc}
            alt="ADEME"
            width="70"
            height="80"
          />
        </div>
      </div>
      <div className="fr-header__navbar">
        <button
          data-fr-opened={modalOpened}
          aria-controls="modal-header__menu"
          aria-haspopup="menu"
          title="Menu"
          className="fr-btn--menu fr-btn"
          onClick={() => setModalOpened(!modalOpened)}
        >
          Menu
        </button>
      </div>
    </div>
  );
};

// territoires-en-transitions.fr/src/components/Header.svelte
<header role="banner" class="fr-header">
  <div class="fr-container">
    <div class="fr-header__body-row">
      <div class="fr-header__brand fr-enlarge-link">
        <div class="fr-header__brand-top">
          <div class="fr-header__logo">
            <p class="fr-logo">
              République<br /> française
            </p>
          </div>
        </div>
        <div class="fr-header__ademe">
          <picture>
            <source srcset="static/img/ademe.jpg 118w" sizes="118px">
            <img src="static/img/ademe.jpg" alt="ADEME" loading="lazy">
          </picture>
        </div>
        <div class="fr-header__service">
          <a href="/" title="Accueil">
            <p class="fr-header__service-title">Territoires en Transitions</p>
          </a>
        </div>
      </div>
      <div class="fr-header__tools">
        <div class="fr-header__tools-links">
          <ul class="fr-links-group">
            <li>
              <a href="/" class="fr-link" title="Se connecter">
                <span class="fr-fi-user fr-ds-picto fr-fi--sm fr-mr-2v" /> Se connecter
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="fr-header__menu fr-modal" id="header-navigation" aria-labelledby="button-1">
      <div class="fr-container">
        <button class="fr-link--close fr-link" aria-controls="header-navigation">Fermer</button>
        <div class="fr-header__menu-links" />
      </div>
    </div>
  </div>
</header>

<style>
  .fr-fi--sm {
    font-size: 1rem;
  }
  .fr-ds-picto::before {
    width: 1rem;
    height: 1rem;
    display: block;
    background-repeat: no-repeat;
    background-position: left center;
    content: '';
  }
  .fr-fi-user::before {
    background-image: url("data:image/svg+xml,%3Csvg width='14' height='14' viewBox='0 0 14 14' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill-rule='evenodd' clip-rule='evenodd' d='M6.99919 0.333099C10.6792 0.333099 13.6659 3.31977 13.6659 6.99977C13.6659 10.6798 10.6792 13.6664 6.99919 13.6664C3.31919 13.6664 0.33252 10.6798 0.33252 6.99977C0.33252 3.31977 3.31919 0.333099 6.99919 0.333099ZM3.01452 9.2771C3.99319 10.7371 5.46252 11.6664 7.10585 11.6664C8.74852 11.6664 10.2185 10.7378 11.1965 9.2771C10.087 8.24016 8.62448 7.6643 7.10585 7.66643C5.58699 7.66414 4.12419 8.24001 3.01452 9.2771ZM6.99919 6.3331C8.10376 6.3331 8.99919 5.43767 8.99919 4.3331C8.99919 3.22853 8.10376 2.3331 6.99919 2.3331C5.89462 2.3331 4.99919 3.22853 4.99919 4.3331C4.99919 5.43767 5.89462 6.3331 6.99919 6.3331Z' fill='%23000091'/%3E%3C/svg%3E%0A");
  }

  .fr-header__brand-top {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: flex-start;
    width: auto;
  }
</style>
