// app.territoiresentransitions.react/src/ui/referentiels/ActionReferentielTitle.tsx
import type {ActionReferentiel} from 'generated/models/action_referentiel';

export const ActionReferentielTitle = ({
  action,
  className,
}: {
  action: ActionReferentiel;
  className?: string;
}) => (
  <span className={className ? className : 'text-lg h-8'}>
    {action.id_nomenclature} - {action.nom}
  </span>
);

// app.territoiresentransitions.sveltekit/src/components/shared/ActionReferentiel/ActionReferentielTitle.svelte
<script lang="ts">
    /**
     * Display the title of an action.
     */
    import {ActionReferentiel} from "../../../../../generated/models/action_referentiel";

    export let action: ActionReferentiel

    $: depth = action.id.split('.').length

</script>

<style>
    h3 {
        font-size: 1.25rem;
        line-height: 1.33;
    }
</style>

<h3 on:click|preventDefault>
    <span>{action.id_nomenclature} - </span>
    {action.nom}
</h3>
