// app.territoiresentransitions.fr/src/routes/epcis/index.svelte
<script lang="ts">
    /**
     * Shows all Epcis.
     */
    import {EpciStorable} from "../../storables/EpciStorable";
    import {onMount} from "svelte";
    import {currentUtilisateurDroits} from "../../api/authentication";
    import {UtilisateurDroits} from "../../../../generated/models/utilisateur_droits";

    let allEpcis: EpciStorable[] = []
    let userEpcis: EpciStorable[] = []

    onMount(async () => {
        const stores = await import('../../api/hybridStores')
        const utilisateurDroits: UtilisateurDroits[] = await currentUtilisateurDroits()

        allEpcis = await stores.epciStore.retrieveAll()
        userEpcis = allEpcis.filter((epci) => utilisateurDroits.filter((droits) => droits.ecriture && droits.epci_id === epci.id))
    })
</script>

<div>
    <h2>Bienvenue !</h2>

    {#each userEpcis as epci}
        <p>
            {epci.nom}
            <br>
            <a href="/fiches/?epci_id={epci.uid}">Plan d'action</a>
            <br>
            <a href="/indicateurs/?epci_id={epci.uid}">Indicateurs</a>
        </p>
    {/each}
</div>

<div>
    <h2>Toutes les collectivités</h2>
    {#each allEpcis as epci}
        <p>
            {epci.nom}
            <br>
            <a href="/fiches/?epci_id={epci.uid}">Plan d'action</a>
            <br>
            <a href="/indicateurs/?epci_id={epci.uid}">Indicateurs</a>
        </p>
    {/each}
</div>

// app.territoiresentransitions.react/src/core-logic/hooks/epcis.ts
import {useEffect, useState} from 'react';
import {currentUtilisateurDroits} from 'core-logic/api/authentication';
import {EpciStorable} from 'storables/EpciStorable';
import {useAllStorables} from 'core-logic/hooks/storables';
import {epciStore} from 'core-logic/api/hybridStores';

/**
 * Returns the list of epcis owned by the current user.
 */
export function currentUserEpcis(): EpciStorable[] {
  const all = allSortedEpcis();
  const [epcis, setEpcis] = useState<EpciStorable[]>([]);

  useEffect(() => {
    currentUtilisateurDroits().then(droits => {
      if (droits) {
        const writable = [];
        for (const droit of droits) {
          if (droit.ecriture) {
            for (const epci of all) {
              if (epci.id === droit.epci_id) {
                writable.push(epci);
                break;
              }
            }
          }
        }
        if (!writable.every(s => epcis.includes(s))) setEpcis(writable);
      }
    });
  }, [epcis, all]);

  return epcis;
}

/**
 * Returns all the stored Epcis sorted alphabetically.
 */
export function allSortedEpcis(): EpciStorable[] {
  const allEpcis = useAllStorables<EpciStorable>(epciStore);
  allEpcis.sort((a, b) => a.nom.localeCompare(b.nom));
  return allEpcis;
}
