// app.territoiresentransitions.react/src/app/pages/ActionsReferentiels/_ActionsEconomieCirculaire.tsx
import type { ActionReferentiel } from "generated/models/action_referentiel";

type ActionsEconomieCirculaireProps = {
  actions: ActionReferentiel[];
};

type ActionsByAxe = {
  axe: ActionReferentiel;
  actions: ActionReferentiel[];
  level: 1 | 2;
};

const actionsToActionsByAxe = (
  actions: ActionReferentiel[],
  level: 1 | 2,
): ActionsByAxe[] =>
  actions.map((action) => ({
    level: level,
    actions: action.actions,
    axe: action,
  }));

const getECIActionsByAxes = (actions: ActionReferentiel[]): ActionsByAxe[] => {
  // Filter action based on prefix
  const ECIActions = actions.filter((action) =>
    action.id.startsWith("economie_circulaire"),
  );

  // First axis actions
  const FirstAxisECIActions = actionsToActionsByAxe(ECIActions, 1);

  // const SecondAxisECIActions = ECIActions.reduce(
  //   (acc, action) => [...acc, ...actionsToActionsByAxe(action.actions, 2)],
  //   [] as ActionsByAxe[],
  // );
  return FirstAxisECIActions;

  // const actionsByAxes = new Map<ActionReferentiel, ActionReferentiel[]>();
  // const orientations: ActionReferentiel[] = [];
  // const axes: ActionReferentiel[] = [];

  // for (const action of actions) {
  //   for (const level1 of action.actions) {
  //     axes.push(level1);
  //     for (const level2 of level1.actions) {
  //       orientations.push(level2);
  //     }
  //   }
  // }

  // for (const parent of axes) {
  //   const actions = orientations.filter(
  //     (action) =>
  //       action.id.startsWith(parent.id) &&
  //       action.id.startsWith("economie_circulaire"),
  //   );
  //   if (actions.length) actionsByAxes.set(parent, actions);
  // }
  // return actionsByAxes;
};

export const ActionsEconomieCirculaire = ({
  actions,
}: ActionsEconomieCirculaireProps) => {
  const actionsByAxes = getECIActionsByAxes(actions);
  return (
    <div>
      {actionsByAxes.map((actionsByAxe) => (
        <div>
          <h2 className="fr-h2">
            {actionsByAxe.axe.id_nomenclature} {actionsByAxe.axe.nom}
          </h2>
          {/* <div>Axe : {actionsByAxe.axe.id}</div>
          <div>Actions : {actionsByAxe.actions.length}</div> */}
          {actionsByAxe.actions.map((action) => (
            <ActionReferentielCard action={action} />
          ))}
        </div>
      ))}
    </div>
  );
};

type ActionGenericDescriptionProps = { description: string };

const ActionGenericDescription = ({
  description,
}: ActionGenericDescriptionProps) => {
  if (description) return;
};

type ActionReferentielCardProps = { action: ActionReferentiel };

const ActionReferentielCard = ({ action }: ActionReferentielCardProps) => {
  if (action.actions.length === 0)
    return (
      <article className="bg-yellow-50">
        <h3>
          <span>{action.id_nomenclature} - </span>
          {action.nom}
        </h3>
        <h4> Description </h4>
        <div
          dangerouslySetInnerHTML={{
            __html: action.description,
          }}
        ></div>
      </article>
    );
  else
    return (
      <div>
        {" "}
        {action.actions.map((action) => (
          <ActionReferentielCard action={action} />
        ))}
      </div>
    );
};

// app.territoiresentransitions.react/src/app/pages/ActionsReferentiels/_ActionsEconomieCirculaire.svelte
<script lang="ts">
    import type {ActionReferentiel} from "$generated/models/action_referentiel";
    import ActionReferentielCard from "$components/shared/ActionReferentiel/ActionReferentielCard.svelte";
    import ProgressStat from "$components/shared/ActionReferentiel/ProgressStat.svelte";

    export let searching: boolean

    export let displayed: ActionReferentiel[]

    $: displayed, refresh()

    let displayedByAxe: Map<ActionReferentiel, ActionReferentiel[]>

    const refresh = () => {
        const map = new Map<ActionReferentiel, ActionReferentiel[]>()
        const orientations: ActionReferentiel[] = []
        const axes: ActionReferentiel[] = []

        for (const action of displayed) {
            for (const level1 of action.actions) {
                axes.push(level1)
                for (const level2 of level1.actions) {
                    orientations.push(level2)
                }
            }
        }

        for (let parent of axes) {
            const actions = orientations.filter(
                (action) => action.id.startsWith(parent.id) && action.id.startsWith('economie_circulaire')
            )
            if (actions.length) map.set(parent, actions)
        }
        displayedByAxe = map;
    }

    refresh()
</script>

<style>
    section + section {
        margin-top: 3.75rem;
    }

    h2 {
        display: flex;
        margin-bottom: 1.875rem;
    }

    h2 :global([class^="progressBar"]) {
        flex-shrink: 0;
        margin-left: 1.5rem;
    }

    h2 :global([class^="progressBar"] strong) {
        font-size: 1.125rem;
    }

    h2 :global([class^="progressBar"]) {
        font-size: 1rem;
    }
</style>

{#each [...displayedByAxe] as [parent, actions]}
    <section>
        <h2 class="fr-h2">{parent.id_nomenclature} {parent.nom}</h2>
        <ProgressStat action={parent} position="left"/>
        <div style="height: 4em"></div>
        {#each actions as action}
            {#if searching}
                <ActionReferentielCard action={action} ficheButton expandButton statusBar/>
            {:else }
                <ActionReferentielCard action={action} link/>
            {/if}
        {/each}
    </section>
{/each}
