// app.territoiresentransitions.react/src/ui/referentiels/ActionReferentielTitle.tsx
import type {ActionReferentiel} from 'generated/models/action_referentiel';

export const ActionReferentielTitle = ({
  action,
  className,
}: {
  action: ActionReferentiel;
  className?: string;
}) => (
  <span className={className ? className : 'text-lg h-8'}>
    {action.id_nomenclature} - {action.nom}
  </span>
);

// app.territoiresentransitions.fr/src/components/shared/ActionReferentiel/ActionReferentielTitle.svelte
<script lang="ts">
    /**
     * Display the title of an action.
     */
    import {ActionReferentiel} from "../../../../../generated/models/action_referentiel";

    export let action: ActionReferentiel

    $: depth = action.id.split('.').length

</script>

<h3 on:click|preventDefault>
    <span class="mr-4">{action.id_nomenclature} </span>
    <span class="mr-4">{action.nom}</span>
</h3>
