// app.territoiresentransitions.fr/src/components/shared/ActionReferentiel/ProgressStat.svelte
<script lang="ts">
    import type {ActionReferentielScore} from "$generated/models/action_referentiel_score";
    import {onMount} from "svelte";
    import type {ActionReferentiel} from "$generated/models/action_referentiel";

    export let action: ActionReferentiel
    export let position = "left";
    let score: ActionReferentielScore
    let state = "alert";

    const updateState = () => {
        const percentage: number = score ? score.percentage * 100 : 0
        if (score && score.avancement.includes('non_concernee')) {
            state = "nc"
        }
        else if (percentage < 34) {
            state = "alert"
        }
        else if (percentage < 49) {
            state = "warning"
        }
        else if (percentage < 64) {
            state = "ok"
        }
        else if (percentage < 74) {
            state = "good"
        }
        else {
            state = "best"
        }
    }
    $:score, updateState();


    onMount(async () => {
        const stores = await import("$api/hybridStores")
        score = await stores.actionReferentielScoreStore.retrieveById(action.id)
    })
</script>

<style>
    div {
        padding-left: 0.75rem;
        font-size: 0.875rem;
        font-weight: normal;
        background-color: #fff;
        border-left: 6px solid #000;
    }

    strong {
        font-size: 1rem;
    }

    .progressBar--position-right {
        padding-right: 0.75rem;
        padding-left: 1.5rem;
        border-right: 6px solid #000;
        border-left: 0;
    }

    .progressBar--position-bottom {
        padding-left: 0;
        border-left: 0;
    }

    .progressBar--position-bottom::after {
        content: "";
        display: block;
        width: 50%;
        height: 6px;
        margin: 0 auto;
        background-color: #000;
    }

    .progressBar--status-nc,
    .progressBar--position-bottom.progressBar--status-nc {
        border-color: #444;
    }

    .progressBar--status-alert,
    .progressBar--position-bottom.progressBar--status-alert {
        border-color: #DA0505;
    }

    .progressBar--status-warning,
    .progressBar--position-bottom.progressBar--status-warning {
        border-color: #F59E0B;
    }

    .progressBar--status-ok,
    .progressBar--position-bottom.progressBar--status-ok {
        border-color: #FCD34D;
    }

    .progressBar--status-good,
    .progressBar--position-bottom.progressBar--status-good {
        border-color: #C0D72D;
    }

    .progressBar--status-best,
    .progressBar--position-bottom.progressBar--status-best {
        border-color: #059669;
    }
</style>

<div class={`progressBar--position-${position} progressBar--status-${state}`}>
    {#if state == "nc"}
        {"non concernée"}
    {:else}
        {#if score}
            <strong>{(score.percentage * 100).toFixed(1)}%</strong>
            ({score.points.toFixed(2)} / {score.potentiel.toFixed(2)})
        {:else }
            <strong>0%</strong>
            (../..)
        {/if}
    {/if}
    
</div>

// app.territoiresentransitions.react/src/ui/referentiels/ProgressStat.tsx
import {useAppState} from 'core-logic/overmind';
import type {ActionReferentielScoreInterface} from 'generated/models/action_referentiel_score';
import {ActionReferentiel} from 'generated/models/action_referentiel';
import {useEffect, useState} from 'react';
import {makeStyles} from '@material-ui/core';

type ProgressState = 'nc' | 'alert' | 'warning' | 'ok' | 'good' | 'best';

const inferStateFromScore = (
  score?: ActionReferentielScoreInterface
): ProgressState => {
  const percentage: number = score ? score.percentage * 100 : 0;
  if (score && score.avancement.includes('non_concernee')) {
    return 'nc';
  } else if (percentage < 34) {
    return 'alert';
  } else if (percentage < 49) {
    return 'warning';
  } else if (percentage < 64) {
    return 'ok';
  } else if (percentage < 74) {
    return 'good';
  } else {
    return 'best';
  }
};

const useStyle = makeStyles({
  nc: {
    borderColor: '#444',
  },
  alert: {
    borderColor: '#DA0505',
  },
  warning: {
    borderColor: '#F59E0B',
  },
  ok: {
    borderColor: '#FCD34D',
  },
  good: {
    borderColor: '#C0D72D',
  },
  best: {
    borderColor: '#059669',
  },
});

const ProgressStatText = ({
  score,
}: {
  score?: ActionReferentielScoreInterface;
}) => {
  const percentageText = score
    ? `${(score.percentage * 100).toFixed(1)}% `
    : '0% ';
  const pointsRatioText = score
    ? `(${score.points.toFixed(2)}/${score.potentiel.toFixed(2)})`
    : '(../..)';

  if (score?.avancement === 'non_concernee') {
    return <span className="text-gray-700"> non concernée</span>;
  }
  return (
    <>
      <strong className="font-bold">{percentageText}</strong>
      {pointsRatioText}
    </>
  );
};

export const ProgressStat = ({
  action,
  position,
  className,
}: {
  action: ActionReferentiel;
  position: 'left' | 'right';
  className?: string;
}) => {
  const classes = useStyle();

  const actionId = action.id;
  const score = useAppState().actionReferentielScoresById[actionId];

  useEffect(() => {
    const state = inferStateFromScore(score);
    setState(state);
  }, [score]);

  const [state, setState] = useState<ProgressState>('nc');

  const positionDependentStyle =
    position === 'left'
      ? 'bl-8 pl-3 border-l-8'
      : 'bl-0 br-8 pl-2 pr-3 border-r-8';

  return (
    <div
      className={`py-1 text-base font-normal bg-white  bg-y ${classes[state]} ${
        className ? className : ''
      } ${positionDependentStyle}`}
    >
      <ProgressStatText score={score} />
    </div>
  );
};
