// app.territoiresentransitions.react/src/app/pages/Indicateurs/Indicateurs.tsx

import "app/DesignSystem/core.css";
import {indicateurs} from "generated/data/indicateurs_referentiels";
import {IndicateurReferentielCard} from "./IndicateurReferentielCard";



export const Indicateurs = () => {
    return (

        <div className="app mx-5 mt-5">
            <h1>Indicateurs</h1>
            <section className="flex flex-col">
                {indicateurs.map((indicateur) => (
                    <IndicateurReferentielCard indicateur={indicateur}/>
                ))}
            </section>
        </div>
    );
};

// client_new/src/routes/indicateurs/index.svelte
<script lang="ts">
    import {IndicateurReferentiel} from "../../../generated/models/indicateur_referentiel";
    import {indicateurs} from "../../../generated/data/indicateurs_referentiels";
    import IndicateurReferentielCard from "../../components/shared/IndicateurReferentielCard.svelte";

    let allIndicateurs: IndicateurReferentiel[] = indicateurs
</script>

{#each indicateurs as indicateur}
    <IndicateurReferentielCard indicateur={indicateur}/>
{/each}
