// app.territoiresentransitions.fr/src/components/shared/Forms/LabeledTextInput.svelte
<script lang="ts">
    /**
     * A text input with a label on top
     *
     * One can use the label prop to display an _unstyled_ text on top of the textarea.
     * In order to style the label text, a child element should be passed instead.
     */
    import type {Validator} from "$api/validator";
    import {alwaysValid} from "$api/validator";
    import {onMount} from "svelte";
    import {v4 as uuid} from 'uuid'

    // The text input value, must be set.
    export let value: string | number

    // An optional unstyled label text.
    export let label: string = ''

    // An optional unstyled hint text.
    export let hint: string = ''

    // An optional prop passed to textarea.
    export let maxlength: number = undefined

    // An optional validator
    export let validator: Validator = alwaysValid

    // An optional id for label and input link
    export let id: string = uuid()

    // Show the validator message on mount.
    export let validateOnMount: boolean = true

    let errorMessage: string | null = null

    onMount(() => {
        if (validateOnMount)
            errorMessage = validator(value)
    })
</script>

<style>
    fieldset {
        max-width: 50%;
    }

    .hint {
        margin-top: .25rem;
        font-size: 0.75rem;
        color: var(--g600);
    }

    input {
        margin-top: .5rem;
    }
</style>

<fieldset>
    <label class="fr-label" for="{id}">{label}
        <slot></slot>
    </label>

    {#if !errorMessage && hint}
        <div class="hint">{hint}</div>
    {/if}

    {#if errorMessage}
        <div class="hint">
            {errorMessage}
        </div>
    {/if}

    <input bind:value={value}
           class="fr-input"
           id="{id}"
           maxlength={maxlength}
           on:keyup={() => errorMessage=validator(value)}
    >
</fieldset>

// app.territoiresentransitions.react/src/ui/forms/LabeledTextInput.tsx
import {alwaysValid, Validator} from "core-logic/api/validator";

import {v4 as uuid} from 'uuid'
import {useState} from "react";

type LabeledTextInputProps = {
    label: string;
    maxLength?: number;
    onChange: (value: string) => void;
    validator: Validator;
    maxlength: number | undefined;
    id: string | undefined;
    validateOnMount: boolean;
    hint: string;
    initialValue: String,
};

const labeledTextInputDefaultProps = {
    validator: alwaysValid,
    validateOnMount: true,
    initialValue: '',
    hint: '',
};

/**
 * A text input with a label on top
 *
 * One can use the label prop to display an _unstyled_ text on top of the textarea.
 * In order to style the label text, a child element should be passed instead.
 */
const LabeledTextInput = (props: LabeledTextInputProps) => {

    const htmlId = props.id ?? uuid();

    const [errorMessage, setErrorMessage] = useState<String | null>(
        props.validateOnMount ?
            props.validator(props.initialValue) :
            null
    );


    return (
        <fieldset>
            <label className="fr-label" htmlFor={htmlId}>
                {props.label}
                <slot/>
            </label>

            {(!errorMessage && props.hint) && <div className="hint">{props.hint}</div>}
            {errorMessage !== null && <div className="hint">{errorMessage}</div>}

            <input
                id={htmlId}
                className="fr-input"
                maxLength={props.maxLength}
                onChange={(e) => {
                    setErrorMessage(props.validator(e.target.value))
                    props.onChange(e.target.value);
                }}
            />
        </fieldset>
    );
};

LabeledTextInput.defaultProps = labeledTextInputDefaultProps;

export default LabeledTextInput;
