// app.territoiresentransitions.react/src/ui/referentiels/ActionReferentielTitle.tsx
import type {ActionReferentiel} from 'generated/models/action_referentiel';

export const ActionReferentielTitle = ({
  action,
  className,
}: {
  action: ActionReferentiel;
  className?: string;
}) => (
  <span className={className ? className : 'text-lg h-8'}>
    {action.id_nomenclature} - {action.nom}
  </span>
);

// client_new/src/components/shared/ActionReferentielTitle.svelte
<script lang="ts">
    import {ActionReferentiel} from "../../../generated/models/action_referentiel";

    export let action: ActionReferentiel

    // Show referentiel emoji
    export let emoji: boolean = false


    $: depth = action.id.split('.').length

</script>

<h3 class="flex flex-grow">
    {#if emoji}
        <span class="mr-1">{action.id.startsWith('citergie') ? '🌍' : '♻'} </span>
    {/if}
    <span class="mr-4">{action.id_nomenclature} </span>
    <span class="mr-4">{action.nom}</span>
</h3>
