// app.territoiresentransitions.react/src/app/pages/collectivite/Indicateurs/IndicateurPersonnaliseCreationDialog.tsx
import React from 'react';
import {IndicateurPersonnaliseStorable} from 'storables/IndicateurPersonnaliseStorable';
import {v4 as uuid} from 'uuid';

import {IndicateurPersonnaliseInterface} from 'generated/models/indicateur_personnalise';
import {useEpciId} from 'core-logic/hooks';
import {IndicateurPersonnaliseForm} from 'app/pages/collectivite/Indicateurs/IndicateurPersonnaliseForm';
import {indicateurPersonnaliseStore} from 'core-logic/api/hybridStores';
import {UiDialogButton} from 'ui/UiDialogButton';

export const IndicateurPersonnaliseCreationDialog = ({
  buttonClasses,
}: {
  buttonClasses?: string;
}) => {
  const [editing, setEditing] = React.useState<boolean>(false);
  const epciId = useEpciId();
  const freshData = (): IndicateurPersonnaliseInterface => {
    return {
      epci_id: epciId!,
      uid: uuid(),
      custom_id: '',
      nom: '',
      description: '',
      unite: '',
      meta: {
        commentaire: '',
      },
    };
  };

  const [data, setData] = React.useState<IndicateurPersonnaliseInterface>(
    freshData()
  );

  const onSave = (indicateur: IndicateurPersonnaliseInterface) => {
    indicateurPersonnaliseStore.store(
      new IndicateurPersonnaliseStorable(indicateur)
    );
    setData(freshData());
    setEditing(false);
  };

  return (
    <UiDialogButton
      title="Créer un nouvel indicateur"
      opened={editing}
      setOpened={setEditing}
      buttonClasses={buttonClasses}
    >
      <IndicateurPersonnaliseForm indicateur={data} onSave={onSave} />
    </UiDialogButton>
  );
};

// app.territoiresentransitions.fr/src/components/shared/IndicateurPersonnalise/IndicateurPersonnaliseCreationDialog.svelte
<script lang="ts">
    import IndicateurForm from './IndicateurPersonnaliseForm.svelte'
    import {createEventDispatcher, onMount} from "svelte";
    import {getCurrentEpciId} from "$api/currentEpci";
    import {v4 as uuid} from 'uuid'
    import type {IndicateurPersonnaliseInterface} from "$generated/models/indicateur_personnalise";
    import Dialog from "../Dialog.svelte";

    let data: IndicateurPersonnaliseInterface
    const dispatch = createEventDispatcher()
    const initialize = () => {
        data = {
            epci_id: '',
            uid: uuid(),
            custom_id: '',
            nom: '',
            description: '',
            unite: '',
            meta: {
                commentaire: ''
            }
        }
    }

    const handleSave = async (event: any) => {
        dispatch('save', event.detail)
        initialize()
        close(event)
    }

    onMount(async () => {
        data.epci_id = getCurrentEpciId()
    });

    initialize()

    const close = (event: MouseEvent) => dispatch('AddDialogClose', event)

</script>


<Dialog ariaLabelledBy="dialog-title"
        handleClose={close}
        size="small">

    <span slot="modal-title">Nouvel indicateur</span>

    <IndicateurForm bind:data={data} on:save={handleSave}/>
</Dialog>
