// app.territoiresentransitions.react/src/app/pages/Epcis/_EpciCard.tsx
import { Link } from "react-router-dom";
import type { EpciStorable } from "storables/EpciStorable";

type EpciCardProps = { epci: EpciStorable };
export const EpciCard = ({ epci }: EpciCardProps) => (
  <div className="flex flex-col items-center pt-8 pr-6 pb-6">
    <h3 className="fr-h3 mb-6">{epci.nom}</h3>
    <button
      className="fr-btn fr-btn--secondary fr-btn--sm fr-fi-arrow-right-line fr-btn--icon-right"
      onClick={() => console.log('goto("fiches", epci.uid)')}
    >
        Plan d'actions
    </button>

      <Link
          className="fr-btn fr-btn--secondary fr-btn--sm fr-fi-arrow-right-line fr-btn--icon-right"
          to={`${epci.id}/actions_referentiels`}
      >
          Référentiels
      </Link>


      <Link
          className="fr-btn fr-btn--secondary fr-btn--sm fr-fi-arrow-right-line fr-btn--icon-right"
          to={`${epci.id}/indicateurs`}
      >
          Indicateurs
      </Link>

  </div>
);

// app.territoiresentransitions.sveltekit/src/routes/epcis/_EpciCard.svelte
<script lang="ts">
    /**
     * Display an Epci in an card
     */
    import type {EpciStorable} from "$storables/EpciStorable";

    export let epci: EpciStorable
    export let writable: boolean = false

    $: color = writable ? 'juniper' : 'blueberry'

    const goto = (section: string, epciId: string) => {
        window.location.href = `/${section}/?epci_id=${epciId}`
    }
</script>

<style>
    div {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 2rem 1.5rem 1.5rem;
        background-color: var(--beige);
    }

    h3 {
        margin-bottom: 1.5rem;
        text-align: center;
    }

    .fr-btn:not(:first-of-type) {
        margin-top: 1.25rem;
    }
</style>

<div>
    <h3>{epci.nom}</h3>

    <button class="fr-btn fr-btn--secondary fr-btn--sm fr-fi-arrow-right-line fr-btn--icon-right"
            on:click={() => goto('fiches', epci.uid)}>Plan d'actions
    </button>

    <button class="fr-btn fr-btn--secondary fr-btn--sm fr-fi-arrow-right-line fr-btn--icon-right"
            on:click={() => goto('actions_referentiels',epci.uid)}>Référentiels
    </button>

    <button class="fr-btn fr-btn--secondary fr-btn--sm fr-fi-arrow-right-line fr-btn--icon-right"
            on:click={() => goto('indicateurs', epci.uid)}>Indicateurs
    </button>
</div>
