// app.territoiresentransitions.react/src/app/pages/Epcis/Epcis.tsx
import { Route } from "type-route";
import { routes } from "app/Router";
import { AddDialog } from "./_AddDialog";

import "app/DesignSystem/buttons.css";
import "app/DesignSystem/core.css";
import "app/DesignSystem/variables.css";

import { makeStyles } from "@material-ui/core";
import React from "react";
import { overmind } from "core-logic/overmind";
import { EpciCard } from "./_EpciCard";

type EpcisProps = { route: Route<typeof routes.epcis> };

const useStyle = makeStyles({
  card: {
    display: "flex",
    alignItems: "center",
    padding: "2rem 1.5rem 1.125rem",
    backgroundColor: "var(--beige)",
    borderBottom: "4px solid var(--bf500)", // var(--bf500)
    flexDirection: "column",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gridGap: "3rem",
  },
});

export const Epcis = (props: EpcisProps) => {
  const classes = useStyle();
  const [addEpciDialogOpen, setAddEpciDialogOpen] = React.useState(false);

  const handleClickOpen = () => {
    setAddEpciDialogOpen(true);
  };

  return (
    <div className="app mx-5 mt-5">
      <section>
        <h1 className="fr-h1 mb-16 text-center">Bienvenue !</h1>

        <h2 className="fr-h2 mb-20 text-center">Vos collectivités</h2>

        <div className={classes.grid}>
          {/* {#each userEpcis as epci}
                <Card epci={epci} writable/>
            {/each} */}
          <div className={classes.card}>
            <h3 className="fr-h3">…</h3>
            <button className="fr-btn fr-btn--sm" onClick={handleClickOpen}>
              Ajouter ma collectivité
            </button>
          </div>
        </div>
      </section>

      <section>
        <h2 className="fr-h2 mb-20 text-center">
          Consulter toutes les collectivités
        </h2>

        <div className={classes.grid}>
          {overmind.state.allEpcis.map((epci) => (
            <EpciCard epci={epci} />
          ))}
          {/* {#each allEpcis as epci}
                <Card epci={epci}/>
            {/each} */}
        </div>
      </section>
      <AddDialog
        epcis={overmind.state.allEpcis}
        open={addEpciDialogOpen}
        close={() => {
          setAddEpciDialogOpen(false);
        }}
      />
    </div>
  );
};

// app.territoiresentransitions.sveltekit/src/routes/epcis/index.svelte
<script lang="ts">
    /**
     * Shows all Epcis.
     */
    import type {EpciStorable} from "$storables/EpciStorable";
    import {onMount} from "svelte";
    import {currentUtilisateurDroits} from "$api/authentication";
    import type {UtilisateurDroits} from "$generated/models/utilisateur_droits";
    import AddDialog from "./_AddDialog.svelte"
    import Card from "./_EpciCard.svelte"

    let allEpcis: EpciStorable[] = []
    let userEpcis: EpciStorable[] = []
    let showAddDialog: boolean = false

    const fetch = async () => {
        const stores = await import('$api/hybridStores')
        const utilisateurDroits: UtilisateurDroits[] = await currentUtilisateurDroits()

        const all = await stores.epciStore.retrieveAll()
        allEpcis = all.sort((a, b) => a.nom > b.nom ? 1 : -1)
        userEpcis = allEpcis.filter((epci) => {
            return utilisateurDroits.filter((droits) => {
                return droits.ecriture && droits.epci_id === epci.id
            }).length > 0
        })
    }

    const handleDialogClose = async () => {
        showAddDialog = false
        await fetch()
    }

    onMount(fetch)
</script>

<style>
    section + section {
        margin-top: 11.25rem;
    }

    .grid {
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        grid-gap: 3rem;
    }

    .card {
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 2rem 1.5rem 1.125rem;
        background-color: var(--beige);
        border-bottom: 4px solid var(--bf500);
    }

    h1,
    h2 {
        text-align: center;
    }

    h1 {
        margin-bottom: 3.75rem;
    }

    h2 {
        margin-bottom: 4.5rem;
    }
</style>

<section>
    <h1>Bienvenue !</h1>

    <h2>Vos collectivités</h2>

    <div class="grid">
        {#each userEpcis as epci}
            <Card epci={epci} writable/>
        {/each}

        <div class="card">
            <h3>…</h3>
            <button class="fr-btn fr-btn--sm" on:click|preventDefault={() => showAddDialog = !showAddDialog}>Ajouter ma
                collectivité
            </button>
        </div>
    </div>
</section>

<section>
    <h2>Consulter les autres collectivités</h2>

    <div class="grid">
        {#each allEpcis as epci}
            <Card epci={epci}/>
        {/each}
    </div>
</section>


{#if showAddDialog}
        <AddDialog
                          epcis={allEpcis}
                          on:AddDialogClose={handleDialogClose}
        />
{/if}
