// app.territoiresentransitions.react/src/ui/Footer.tsx
import "app/DesignSystem/footer.css";
import "app/DesignSystem/logo.css";
import React from "react";

export type FooterProps = {
  description: React.ReactElement;
  navigation: React.ReactElement;
};

export const FooterNavigation = () => (
  <div className="fr-footer__bottom">
    <ul className="fr-footer__bottom-list">
      <li className="fr-footer__bottom-item">
        <a
          className="fr-footer__bottom-link"
          href="https://territoiresentransitions.fr/mentions-legales/"
          target="_self"
        >
          Mentions légales
        </a>
      </li>
      <li className="fr-footer__bottom-item">
        <a
          className="fr-footer__bottom-link"
          href="https://www.ademe.fr/lademe/infos-pratiques/politique-protection-donnees-a-caractere-personnel"
          rel="external noreferrer"
          target="_blank"
        >
          Protection des données
        </a>
      </li>
    </ul>
  </div>
);

export const FooterDescription = () => (
  <div>
    <p className="fr-footer__content-desc">
      Territoires en transitions accompagne les collectivités afin de les aider
      à piloter plus facilement leur transition écologique.
    </p>
    <p className="fr-footer__content-desc">
      Vous rencontrez une difficulté ? Une suggestion pour nous aider à
      améliorer l'outil ? Écrivez-nous à :
      <a href="mailto:aide@territoiresentransitions.fr?subject=Aide sur app.territoiresentransitions.fr">
        aide@territoiresentransitions.fr
      </a>
    </p>
  </div>
);

export const Footer = (props: FooterProps) => {
  return (
    <footer
      className="footer fr-footer fr-mt-10w"
      role="contentinfo"
      id="footer"
    >
      <div className="fr-container">
        <div className="fr-footer__body">
          <div className="fr-footer__brand fr-enlarge-link">
            <p className="fr-logo" title="république française">
              république
              <br />
              française
            </p>
            <div className="fr-footer__logo fr-p-1w">
              <picture>
                <source
                  src="https://territoiresentransitions.fr/img/ademe.jpg 118w"
                  sizes="118px"
                />
                <img
                  className="footer__logo"
                  height="100"
                  src="https://territoiresentransitions.fr/img/ademe.jpg"
                  alt="ADEME"
                  loading="lazy"
                />
              </picture>
            </div>
            <div className="fr-header__service">
              <a href="https://territoiresentransitions.fr" title="Accueil">
                <p className="fr-header__service-title">
                  Territoires en Transitions
                </p>
              </a>
            </div>
          </div>
          <div className="fr-footer__content">
            {/* <!-- A small sentence in the footer to describe the service --> */}
            {/* <slot name="description"></slot> */}
            {props.description}
            <ul className="fr-footer__content-list">
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="https://www.ademe.fr/"
                >
                  ademe.fr
                </a>
              </li>
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="https://beta.gouv.fr/"
                >
                  beta.gouv
                </a>
              </li>
              <li className="fr-footer__content-item">
                <a
                  className="fr-footer__content-link"
                  href="http://citergie.ademe.fr/"
                >
                  citergie.fr
                </a>
              </li>
            </ul>
          </div>
        </div>
        {props.navigation}
      </div>
    </footer>
  );
};

// app.territoiresentransitions.fr/src/components/shared/Layout/Footer.svelte
<script>
    import Footer from '$components/shared/DesignSystem/Footer.svelte'
</script>

<Footer />

<footer class="footer fr-footer fr-mt-10w" role="contentinfo" id="footer">
    <div class="fr-container">
        <div class="fr-footer__body">
            <div class="fr-footer__brand fr-enlarge-link">
                <p class="fr-logo" title="république française">
                    république
                    <br>française
                </p>
                <div class="fr-footer__logo fr-p-1w">
                    <picture>
                        <source srcset="https://territoiresentransitions.fr/img/ademe.jpg 118w" sizes="118px" />
                        <img class="footer__logo" height="100" src="https://territoiresentransitions.fr/img/ademe.jpg" alt="ADEME" loading="lazy" />
                    </picture>
                </div>
                <div class="fr-header__service">
                    <a href="https://territoiresentransitions.fr" title="Accueil">
                        <p class="fr-header__service-title">Territoires en Transitions</p>
                    </a>
                </div>
            </div>
            <div class="fr-footer__content">
                <!-- A small sentence in the footer to describe the service -->
                <slot name="description"></slot>

                <ul class="fr-footer__content-list">
                    <li class="fr-footer__content-item">
                        <a class="fr-footer__content-link" href="https://www.ademe.fr/">ademe.fr</a>
                    </li>
                    <li class="fr-footer__content-item">
                        <a class="fr-footer__content-link" href="https://beta.gouv.fr/">beta.gouv</a>
                    </li>
                    <li class="fr-footer__content-item">
                        <a class="fr-footer__content-link" href="http://citergie.ademe.fr/">citergie.fr</a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- The footer navigation bar -->
        <slot name="navigation"></slot>

    </div>
</footer>
<style>
    .footer :global(.fr-footer__brand .fr-logo::after) {
        min-width: 1.96875rem;
        background-size: 3.9375rem 2.8125rem;
        background-position: 0 calc(100% + 1.40625rem);
        padding-top: 1.65625rem;
    }

    .footer :global(.fr-footer__brand .fr-logo) {
        font-size: 0.7875rem;
    }

    .footer :global(.fr-footer__logo) {
        width: auto;
    }
</style>
