// app.territoiresentransitions.sveltekit/src/routes/fiches/_CategoriePicker.svelte
<script lang="ts">
    /**
     * Note this is a kind of reverse picker as the `fiche action id` is added to the catégorie.
     */

    import CategorieCreation from './_CategorieCreation.svelte'
    import {FicheActionCategorieStorable} from "../../storables/FicheActionCategorieStorable";
    import {onMount} from "svelte";
    import type     {HybridStore} from "../../api/hybridStore";

    export let ficheActionUid: string
    const defaultCategorie = new FicheActionCategorieStorable({
        uid: '',
        epci_id: '',
        nom: '-',
        parent_uid: '',
        fiche_actions_uids: [ficheActionUid]
    })
    let categories: FicheActionCategorieStorable[] = []
    let selected: FicheActionCategorieStorable
    let categorieStore: HybridStore<FicheActionCategorieStorable>

    /**
     * On user interaction with the select element.
     */
    const onSelect = async (_) => {
        await updateCategories()
    }

    /**
     * Update and save categories that needs to be updated.
     */
    const updateCategories = async () => {
        let changed: FicheActionCategorieStorable[] = []
        // Cleanup
        for (let categorie of categories) {
            // search for categories with this fiche uid excluding selected.
            if (selected && selected.uid === categorie.uid) continue
            if (categorie.fiche_actions_uids.includes(ficheActionUid)) {
                // remove id & add categorie to changed
                categorie.fiche_actions_uids = categorie.fiche_actions_uids.filter((uid) => uid != ficheActionUid)
                changed.push(categorie)
            }
        }

        // Update
        if (selected && !selected.fiche_actions_uids.includes(ficheActionUid)) {
            // add this fiche uid to selected categorie
            selected.fiche_actions_uids.push(ficheActionUid)
            // add selected to changed
            changed.push(selected)
        }

        // Save all changed
        for (let categorie of changed) {
            if (categorie.uid) await categorieStore.store(categorie)
        }
        refreshSelection()
    }

    let visibleCategorieCreation = false
    const handleNewCategorie = (_) => {
        visibleCategorieCreation = true
    }

    const onCategorieSave = async (_) => {
        visibleCategorieCreation = false
        selected = null
        await updateCategories()
        categories = await categorieStore.retrieveAll()
        refreshSelection()
    }

    const refreshSelection = () => {
        for (let categorie of categories) {
            if (categorie.fiche_actions_uids.includes(ficheActionUid)) {
                selected = categorie
                return;
            }
        }
        selected = null
    }

    onMount(async () => {
        const hybridStores = await import ("../../api/hybridStores");
        categorieStore = hybridStores.ficheActionCategorieStore;
        categories = await categorieStore.retrieveAll()
        categories.push(defaultCategorie)
        refreshSelection()
    })
</script>

<style>
    fieldset {
        max-width: 75%;
    }

    div {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    select {
        margin-top: .5rem;
    }
</style>

<fieldset>
    <div>
        <label class="fr-label" for="categorie_picker">Catégorie</label>

        <button class="fr-btn fr-btn--secondary fr-btn--sm"
                on:click|preventDefault={handleNewCategorie}>
            Nouvelle catégorie
        </button>
    </div>

    <select bind:value={selected}
            class="fr-select"
            id="categorie_picker"
            on:change={onSelect}
            on:blur={onSelect}>
        {#each categories as categorie}
            <option value={categorie}>
                {categorie.nom}
            </option>
        {/each}
    </select>

    {#if visibleCategorieCreation}
    <CategorieCreation
            ficheActionUid={ficheActionUid}
            on:save={onCategorieSave}/>
    {/if}
</fieldset>

// app.territoiresentransitions.react/src/app/pages/collectivite/PlanActions/Forms/CategoriePicker.tsx
import {FicheActionCategorieStorable} from 'storables/FicheActionCategorieStorable';
import {ficheActionCategorieStore} from 'core-logic/api/hybridStores';
import {useAllStorables, useEpciId} from 'core-logic/hooks';
import React, {useState} from 'react';
import {FormControl, MenuItem, Select} from '@material-ui/core';
import {defaultCategorie} from 'app/pages/collectivite/PlanActions/defaultCategorie';
import {FicheActionCategorieInterface} from 'generated/models/fiche_action_categorie';
import {v4 as uuid} from 'uuid';
import {CategoryForm} from 'app/pages/collectivite/PlanActions/Forms/CategoryForm';

function CategorieCreation(props: {ficheUid: string; onSave: () => void}) {
  const epciId = useEpciId();
  const categorie: FicheActionCategorieInterface = {
    epci_id: epciId!,
    uid: uuid(),
    parent_uid: '',
    nom: '',
    fiche_actions_uids: [props.ficheUid],
  };
  return <CategoryForm categorie={categorie} onSave={props.onSave} />;
}

/**
 * Pick a categorie for a given fiche uid.
 *
 * Note this is a kind of reverse picker as the `fiche action id`
 * is added to the catégorie as fiche is unaware of the categories it
 * belongs to.
 */
export function CategoriePicker(props: {ficheUid: string}) {
  const categories = useAllStorables<FicheActionCategorieStorable>(
    ficheActionCategorieStore
  );
  const [creating, setCreating] = useState<boolean>(false);

  const ficheActionUid = props.ficheUid;
  const active = categories.find(cat =>
    cat.fiche_actions_uids.includes(props.ficheUid)
  );

  /**
   * Update and save categories that needs to be updated.
   *
   * It's a three step thing to ensure everything is in sync.
   */
  const selectCategorie = (selectedUid: string) => {
    const changed: FicheActionCategorieStorable[] = [];
    // Cleanup
    for (const categorie of categories) {
      // search for categories with this fiche uid excluding selected.
      if (selectedUid === categorie.uid) continue;
      if (categorie.fiche_actions_uids.includes(ficheActionUid)) {
        // remove id & add categorie to changed
        categorie.fiche_actions_uids = categorie.fiche_actions_uids.filter(
          uid => uid !== ficheActionUid
        );
        changed.push(categorie);
      }
    }

    // Update selected
    const selected = categories.find(cat => cat.uid === selectedUid);
    if (selected && !selected.fiche_actions_uids.includes(ficheActionUid)) {
      // add this fiche uid to selected categorie
      selected.fiche_actions_uids.push(ficheActionUid);
      // add selected to changed
      changed.push(selected);
    }

    // Save all changed
    for (const categorie of changed) {
      if (categorie.uid) ficheActionCategorieStore.store(categorie);
    }
  };

  return (
    <fieldset className="flex flex-col ">
      <div className="flex flex-row w-full space-between items-center">
        <label className="fr-label" htmlFor="categorie_picker">
          Catégorie
        </label>

        {!creating && (
          <button
            className="fr-btn fr-btn--secondary fr-btn--sm"
            onClick={e => {
              e.preventDefault();
              setCreating(true);
            }}
          >
            Nouvelle catégorie
          </button>
        )}
      </div>
      {!creating && (
        <FormControl>
          <Select
            className="bg-beige"
            value={active?.uid ?? defaultCategorie.uid}
            onChange={event => selectCategorie(`${event.target.value}`)}
          >
            <MenuItem value={defaultCategorie.uid} key={defaultCategorie.uid}>
              {defaultCategorie.nom}
            </MenuItem>
            {categories.map(cat => (
              <MenuItem value={cat.uid} key={cat.uid}>
                {cat.nom}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
      )}
      {creating && (
        <div className="flex flex-col border-bf500 border-l-4 p-4 mt-2 mb-5 ml-5 bg-beige max-w-2xl">
          <div className="flex flex-row  w-full items-center justify-between">
            <h5 className="text-lg">Nouvelle catégorie</h5>
            <button className="fr-btn" onClick={() => setCreating(false)}>
              x
            </button>
          </div>
          <CategorieCreation
            ficheUid={props.ficheUid}
            onSave={() => setCreating(false)}
          />
        </div>
      )}
    </fieldset>
  );
}
